version: '3'
services:
  flask-proxy:
    build: .
    ports:
      - "80:5001"
    environment:
      DESTINATION_URL: https://api.cinex.pro/api/payment/checkout
      SECRET_KEY: your_secret_key_here
      RATE_LIMIT: 10 per minute
      DEBUG: 'True'
      PORT: 5001
