version: '3'
services:
  flask-proxy:
    build: .
    ports:
      - "5001:5001"
    environment:
      DESTINATION_URL: https://830c89d2-1d8c-4d08-ab5e-ce886d3bd24f.cinex.pro
      SECRET_KEY: web-hook
      RATE_LIMIT: 10 per minute
      DEBUG: 'False'
      PORT: 5001
    volumes:
      - ./logs:/app/logs

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /path/to/your/ssl:/etc/nginx/ssl:ro
    depends_on:
      - flask-proxy
