version: '3'
services:
  flask-proxy:
    build: .
    ports:
      - "80:5001"
    environment:
      DESTINATION_URL: https://api.cinex.pro/api/payment/checkout
      SECRET_KEY: goruboe
      RATE_LIMIT: 10 per minute
      DEBUG: 'False'
      PORT: 5001
    volumes:
      - ./logs:/app/logs