version: '3'
services:
  flask-proxy:
    build: .
    ports:
      - "3103:5000"
    environment:
      DESTINATION_URL: https://api.cinex.pro/api/payment/checkout
      SECRET_KEY: WebHook
      RATE_LIMIT: 10 per minute
      DEBUG: 'False'
      PORT: 3103
    volumes:
      - ./logs:/app/logs

  nginx:
    image: nginx:latest
    ports:
      - "3103:3103"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-proxy